---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/eks-irsa-app-api"
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: app-api
    app.kubernetes.io/part-of: app
  name: app-api