---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-api
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/overskylab/mtl-assignment
    targetRevision: main
    path: manifests/base
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
